### PR TITLE
added auth to expectation, assignment and student

### PR DESCRIPTION
**Pull request by sbilalshaikh**
some sussy things: 

i was able to test the expectation auth, but the student controller currently can't find any students based on uuids. Until we solve this roadblock I won't be able to test assignment or student because they rely on finding a student.

other than that the actual auth code should be fine: if it works for expectation then it should for the other ones.

### CODE REVIEW

**Comment by abeldiress** [comment]
I'll add the student find through uuid function before we merge again

**Comment by sbilalshaikh** [comment]
I fixed the student thing. Ill send another PR when I have tested all the other auth stuff

**Comment by sbilalshaikh** [comment]
Merge pls 🙏🙏🙏🙏🙏

**Review by abeldiress — APPROVED** [review]
LGTM! 🐈🐈

**Pull request merged**
